library(dplyr)
set2 <- read.csv("prod2-clean.csv")
set4 <- read.csv("prod4-clean.csv")
set5 <- read.csv("prod5-clean.csv")
set6 <- read.csv("prod6-clean.csv")
set7 <- read.csv("prod7-clean.csv")
set_list <- c(set2, set4, set5, set6, set7)
set2 <- select(set2, id, name, styleId, style.name, style.shortName, abv, ibu, srmId, originalGravity, isOrganic)
set4 <- select(set4, id, name, styleId, style.name, style.shortName, abv, ibu, srmId, originalGravity, isOrganic)
set5 <- select(set5, id, name, styleId, style.name, style.shortName, abv, ibu, srmId, originalGravity, isOrganic)
set6 <- select(set6, id, name, styleId, style.name, style.shortName, abv, ibu, srmId, originalGravity, isOrganic)
set7 <- select(set7, id, name, styleId, style.name, style.shortName, abv, ibu, srmId, originalGravity, isOrganic)
set <- rbind(set2, set4, set5, set6, set7)
set <- set[!duplicated(set),]
write.csv(set2, "prod2-filtered.csv")
write.csv(set4, "prod4-filtered.csv")
write.csv(set5, "prod5-filtered.csv")
write.csv(set6, "prod6-filtered.csv")
write.csv(set7, "prod7-filtered.csv")
write.csv(set, "prod-merged.csv", row.names=F)
